"""Initial_CMS_Migration

Revision ID: c5b5470dd042
Revises: 
Create Date: 2026-01-09 18:58:24.206296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b5470dd042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('framerate', sa.Integer(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('transition_in', sa.String(), nullable=True),
    sa.Column('transition_out', sa.String(), nullable=True),
    sa.Column('blendshapes_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animation_assets_file_hash'), 'animation_assets', ['file_hash'], unique=False)
    op.create_table('glosses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glosses_name'), 'glosses', ['name'], unique=False)
    op.create_table('sign_languages',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sign_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gloss_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['animation_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gloss_id'], ['glosses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['sign_languages.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_variants')
    op.drop_table('sign_languages')
    op.drop_index(op.f('ix_glosses_name'), table_name='glosses')
    op.drop_table('glosses')
    op.drop_index(op.f('ix_animation_assets_file_hash'), table_name='animation_assets')
    op.drop_table('animation_assets')
    # ### end Alembic commands ###
